### ISSUE TITLE
IdentityAgent identity API REST handlers

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-servers#2]
API REST handlers calling Identity Agent methods:
- [x] POST /identity
- [x] GET /id/:id/mt
- [x] POST /id/:id/claims
- [x] GET /id/:id/claims/emitted
- [x] GET /id/:id/claims/received

#### POST /identity
*Creates new identity & Identity Agent for that identity*

in:
```
{
              claimAuthKOp Claim
              extraGenesisClaims []Claims
}
```

out:
```
{
              id string
              proofOpKey Proof
}
```

#### GET /id/:id/mt
*Get the current MerkleTree of the identity*

out:
```
{
	data map[string]string
}
```

#### POST /id/:id/claims
*Adds the claim into the MerkleTree of the given identity*

in:
```
{
              claim []Claim
			  oldRoot Hash
			  newRoot Hash // locally calculated
			               // by the local copy of MerkleTree
			  signedNewRoot Signature
}
```

#### GET /id/:id/claims/emitted
*Gets the emitted claims by the identity*
out:
```
{
              [] struct{
                            claim Claim
                            proof Proof
              }
}
```

#### GET /id/:id/claims/received
*Gets the received claims by the identity*
out:
```
{
              [] struct{
                            issuer ID
                            claim Claim
                            proof Proof
              }
}
```

**Comment by ed255** [comment]
Maybe we should add an endpoint to publish the root of the identity's merkle tree.  Probably this action will require access to the keystore because the new root will need to be signed by the kOp, and this action may not fit in the endpoints that manipulate the merkle tree because a request to add a claim will not know the new root.

For example, adding a claim could be like this:
# A
```
i.AddClaim(claim) // POST /id/:id/claims
i.GetRoot() // GET /id/:id/root
i.PublishRoot(root) // POST /id/:id/publishroot (here the client will request a signature from the keystore)
```

By looking at the proposal in this issue, I understand that if we have a local copy of the merkle tree we can add a claim and sign the new root all at once.  But will we have a local copy of the merkle tree in the first iteration?

**Comment by ed255** [comment]
Regarding the rest of the endpoints, here are my comments:

### GET /id/:id/claims
Remove it because we can already do the same with `GET /id/:id/claims/received` and `GET /id/:id/claims/emitted`

### GET /id/:id/claims/emitted
Don't return the proofs.  If the user wants proofs, they could use an endpoint to get proofs (either single or batch).  I think reducing the amount of work that each endpoint does to the minimum will lead to better composability.

###

**Comment by arnaucube** [comment]
Deprecated
